name: Android Firebase App Distribution Workflow

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java 17
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Step 3: Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Step 4: Bump version in pubspec.yaml
      - name: Bump Version in pubspec.yaml
        id: bump-version
        run: |
          # Extract the current version
          VERSION=$(grep -oP 'version:\s*\K[0-9]+\.[0-9]+\.[0-9]+(?=\+)' pubspec.yaml)
          BUILD=$(grep -oP 'version:\s*[0-9]+\.[0-9]+\.[0-9]+\+\K[0-9]+' pubspec.yaml)

          # Increment the patch version
          NEW_VERSION=$(echo $VERSION | awk -F. '{print $1 "." $2 "." $3+1}')
          NEW_BUILD=$((BUILD+1))

          # Update the pubspec.yaml file
          sed -i "s/version: $VERSION+$BUILD/version: $NEW_VERSION+$NEW_BUILD/" pubspec.yaml

          echo "New version: $NEW_VERSION+$NEW_BUILD"
          echo "version=$NEW_VERSION+$NEW_BUILD" >> $GITHUB_ENV

      # Step 5: Install project dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 6: Clear Flutter build cache
      - name: Clear Flutter Build Cache
        run: flutter clean

      # Step 7: Build the release APK
      - name: Build APK for Production
        run: flutter build apk --release

      # Step 8: Distribute APK to Firebase
      - name: Distribute APK to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.ANDROID_APP_ID }}
          file: build/app/outputs/flutter-apk/app-release.apk
          groups: maintainers
          releaseNotes: "Automated release with incremented version"
          debug: true
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

      # Step 9: Upload APK as an artifact
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
